In [1]:
# changing directory so I can import
import os
os.chdir('C:\\Users\\15714\\Documents\\repositories\\publicsandbox\\fishing_report_dashboard')


from water_data import get_usgs_water_data

In [ ]:
'''
site
    02055080: ROANOKE RIVER AT THIRTEENTH ST BR AT ROANOKE, VA
    02054750: ROANOKE RIVER AT ROUTE 117 AT ROANOKE, VA
    02056000: ROANOKE RIVER AT NIAGARA, VA
    02055000: ROANOKE RIVER AT ROANOKE, VA

param_cd
    00010: water temperature
    00065: height (feet)
'''

In [3]:
site = '02055000'
param_cd = '00065'
start_dt = '2023-02-20T19:17:43.422-05:00'
end_dt = '2023-02-27T19:17:43.422-05:00'

get_usgs_water_data(site, param_cd, start_dt, end_dt)

     agency_cd  site_no          datetime tz_cd  147471_00065 147471_00065_cd
0         USGS  2055000  2023-02-20 19:20   EST          2.42               P
1         USGS  2055000  2023-02-20 19:25   EST          2.40               P
2         USGS  2055000  2023-02-20 19:30   EST          2.40               P
3         USGS  2055000  2023-02-20 19:35   EST          2.41               P
4         USGS  2055000  2023-02-20 19:40   EST          2.40               P
...        ...      ...               ...   ...           ...             ...
2010      USGS  2055000  2023-02-27 18:55   EST          1.77               P
2011      USGS  2055000  2023-02-27 19:00   EST          1.79               P
2012      USGS  2055000  2023-02-27 19:05   EST          1.80               P
2013      USGS  2055000  2023-02-27 19:10   EST          1.81               P
2014      USGS  2055000  2023-02-27 19:15   EST          1.80               P

[2015 rows x 6 columns]